-- Create the pensioners table first
CREATE TABLE pensioners (
    code TEXT,
    bank_accountnumber TEXT,
    annualbasicsalary TEXT,
    bank_name TEXT,
    bank_branchcode TEXT,
    company TEXT,
    costcentre TEXT,
    currency TEXT,
    dailyrate TEXT,
    dateofbirth TEXT,
    dateofengagement TEXT,
    dateoftermination TEXT,
    department_code TEXT,
    department TEXT,
    employee TEXT,
    firstname TEXT,
    gender TEXT,
    grosspay TEXT,
    hourlyrate TEXT,
    hoursperperiod TEXT,
    maritalstatus TEXT,
    nationalidentificationno TEXT,
    nationality TEXT,
    occupation TEXT,
    paymentbasis TEXT,
    paymentmethod TEXT,
    paymentpointcode TEXT,
    paymentpoint TEXT,
    payroll TEXT,
    personalemailaddress TEXT,
    phoneno TEXT,
    phoneno2 TEXT,
    physicaladdress TEXT,
    physicaladdress2 TEXT,
    position TEXT,
    postaladdress TEXT,
    postaladdress2 TEXT,
    retirementdate TEXT,
    surname TEXT,
    taxationmethod TEXT,
    taxableearnings TEXT,
    totaldeductions TEXT,
    pension TEXT,
    pensionlumpsum TEXT,
    pensionarrearsupload TEXT,
    pensionlumpsumarrearsupload TEXT,
    usdallowance TEXT,
    payecalculated TEXT,
    taxlevy TEXT,
    netpaid TEXT
);
-- Import data from CSV
\copy public.pensioners (
    code, 
    bank_accountnumber, 
    annualbasicsalary, 
    bank_name, 
    bank_branchcode, 
    company, 
    costcentre, 
    currency, 
    dailyrate, 
    dateofbirth, 
    dateofengagement, 
    dateoftermination, 
    department_code, 
    department, 
    employee, 
    firstname, 
    gender, 
    grosspay, 
    hourlyrate, 
    hoursperperiod, 
    maritalstatus, 
    nationalidentificationno, 
    nationality, 
    occupation, 
    paymentbasis, 
    paymentmethod, 
    paymentpointcode, 
    paymentpoint, 
    payroll, 
    personalemailaddress, 
    phoneno, 
    phoneno2, 
    physicaladdress, 
    physicaladdress2, 
    position, 
    postaladdress, 
    postaladdress2, 
    retirementdate, 
    surname, 
    taxationmethod, 
    taxableearnings, 
    totaldeductions, 
    pension, 
    pensionlumpsum, 
    pensionarrearsupload, 
    pensionlumpsumarrearsupload, 
    usdallowance, 
    payecalculated, 
    taxlevy, 
    netpaid
) 
FROM 'C:/Users/RudoMhiripiri/Downloads/ZEIPF Workflow Automation System/ZEIPF Workflow Automation System/client/src/lib/pensioner_csv/Pensionersdetails.csv' 
WITH (
    FORMAT csv, 
    HEADER true, 
    DELIMITER ',', 
    ENCODING 'UTF8', 
    QUOTE '"'
);
'client/src/lib/pensioner_csv/Pensionersdetails.csv'
