-- Create the pensioners table first
CREATE TABLE IF NOT EXISTS pensioners (
    id SERIAL PRIMARY KEY,
    code TEXT NOT NULL,
    bank_accountnumber TEXT,
    annualbasicsalary NUMERIC,
    bank_name TEXT,
    bank_branchcode TEXT,
    company TEXT,
    costcentre TEXT,
    currency TEXT,
    dailyrate NUMERIC,
    dateofbirth DATE,
    dateofengagement DATE,
    dateoftermination DATE,
    department_code TEXT,
    department TEXT,
    employee TEXT,
    firstname TEXT,
    gender TEXT,
    grosspay NUMERIC,
    hourlyrate NUMERIC,
    hoursperperiod NUMERIC,
    maritalstatus TEXT,
    nationalidentificationno TEXT,
    nationality TEXT,
    occupation TEXT,
    paymentbasis TEXT,
    paymentmethod TEXT,
    paymentpointcode TEXT,
    paymentpoint TEXT,
    payroll TEXT,
    personalemailaddress TEXT,
    phoneno TEXT,
    phoneno2 TEXT,
    physicaladdress TEXT,
    physicaladdress2 TEXT,
    position TEXT,
    postaladdress TEXT,
    postaladdress2 TEXT,
    retirementdate DATE,
    surname TEXT,
    taxationmethod TEXT,
    taxableearnings NUMERIC,
    totaldeductions NUMERIC,
    pension NUMERIC,
    pensionlumpsum NUMERIC,
    pensionarrearsupload NUMERIC,
    pensionlumpsumarrearsupload NUMERIC,
    usdallowance NUMERIC,
    payecalculated NUMERIC,
    taxlevy NUMERIC,
    netpaid NUMERIC
);

-- Import data from CSV
COPY public.pensioners (
    code, 
    bank_accountnumber, 
    annualbasicsalary, 
    bank_name, 
    bank_branchcode, 
    company, 
    costcentre, 
    currency, 
    dailyrate, 
    dateofbirth, 
    dateofengagement, 
    dateoftermination, 
    department_code, 
    department, 
    employee, 
    firstname, 
    gender, 
    grosspay, 
    hourlyrate, 
    hoursperperiod, 
    maritalstatus, 
    nationalidentificationno, 
    nationality, 
    occupation, 
    paymentbasis, 
    paymentmethod, 
    paymentpointcode, 
    paymentpoint, 
    payroll, 
    personalemailaddress, 
    phoneno, 
    phoneno2, 
    physicaladdress, 
    physicaladdress2, 
    position, 
    postaladdress, 
    postaladdress2, 
    retirementdate, 
    surname, 
    taxationmethod, 
    taxableearnings, 
    totaldeductions, 
    pension, 
    pensionlumpsum, 
    pensionarrearsupload, 
    pensionlumpsumarrearsupload, 
    usdallowance, 
    payecalculated, 
    taxlevy, 
    netpaid
) 
FROM 'client/src/lib/pensioner_csv/Pensionersdetails.csv' 
DELIMITER ',' 
CSV HEADER 
ENCODING 'UTF8' 
QUOTE '"' 
ESCAPE '''';
